mutation upsertOrganization($namewhere: String,$name: String!,  $owner: UserWhereUniqueInput, $persons: [PersonWhereUniqueInput!]) {
  upsertOrganization(
    where: { name: $namewhere }
    create: {
      name: $name
      owner: { connect: $owner }
      persons: { connect: $persons }
    }
    update: {
      name: $name
      owner: { connect: $owner }
      persons: { connect: $persons } 
    }
  ) {
    id
    name
    owner {
      id
      name
    }
    persons {
      id
    }
  }
}
mutation deleteOrganization($name: String) {
  deleteOrganization(where: { name: $name }) {
    id
    name
    owner {
      id
      name
    }
    persons {
      id
    }
  }
}
query organization($name: String) {
  organization(where: { name: $name }) {
    id
    name
    owner {
      id
      name
    }
    persons {
      id
    }
  }
}
query organizations {
  organizations {
    id
    name
    owner {
      id
      name
    }
    persons {
      id
    }
  }
}
