fragment OrganizationFragment on Organization {
  id
  name
  owner {
    id
  }
  persons {
    id
  }
}
mutation upsertOrganization(
  $namewhere: String
  $name: String!
  $owner: UserWhereUniqueInput
  $persons: [PersonWhereUniqueInput!]
) {
  upsertOrganization(
    where: { name: $namewhere }
    create: {
      name: $name
      owner: { connect: $owner }
      persons: { connect: $persons }
    }
    update: {
      name: $name
      owner: { connect: $owner }
      persons: { connect: $persons }
    }
  ) {
      ...OrganizationFragment
  }
}
mutation deleteOrganization($name: String) {
  deleteOrganization(where: { name: $name }) {
      ...OrganizationFragment
  }
}
query organization($name: String) {
  organization(where: { name: $name }) {
      ...OrganizationFragment
  }
}

query organizations {
  organizations {
      ...OrganizationFragment
  }
}

subscription organizationsub($where: OrganizationSubscriptionWhereInput) {
  organization(where: $where) {
    mutation
    node {
      ...OrganizationFragment
    }
    updatedFields
    previousValues {
      id
      name
    }
  }
}
