mutation upsertStage(
  $name: String!
  $namewhere: String
  $order_nr: String
  $deal_probability: Probability
  $pipeline: PipelineWhereUniqueInput
) {
  upsertStage(
    where: { name: $namewhere }
    create: {
      name: $name
      pipeline: { connect: $pipeline }
      order_nr: $order_nr
      deal_probability: $deal_probability
    }
    update: {
      name: $name
      pipeline: { connect: $pipeline }
      order_nr: $order_nr
      deal_probability: $deal_probability
    }
  ) {
    id
    name
    pipeline {
      id
    }
    order_nr
    deal_probability
  }
}
mutation deleteStage($name: String) {
  deleteStage(where: { name: $name }) {
    id
    name
    pipeline {
      id
    }
    order_nr
    deal_probability
  }
}
query stage($name: String) {
  stage(where: { name: $name }) {
    id
    name
    pipeline {
      id
    }
    order_nr
    deal_probability
  }
}
query stages {
  stages {
    id
    name
    pipeline {
      id
    }
    order_nr
    deal_probability
  }
}
