fragment PictureFragment on Picture {
  id
  file
}

mutation upsertPicture($id: ID!, $file: String!) {
  upsertPicture(
    where: { id: $id }
    create: { file: $file }
    update: { file: $file }
  ) {
    ...PictureFragment
  }
}
mutation deletePicture($id: ID) {
  deletePicture(where: { id: $id }) {
    ...PictureFragment
  }
}
query picture($id: ID) {
  picture(where: { id: $id }) {
    ...PictureFragment
  }
}
query pictures {
  pictures {
    ...PictureFragment
  }
}

subscription picturesub($where: PictureSubscriptionWhereInput) {
  picture(where: $where) {
    node {
      ...PictureFragment
    }
    updatedFields
    previousValues {
      id
      name
    }
  }
}
