mutation upsertProduct(
    $name: String!
    $description: String
    $brandId: ID!
    $categoryId: ID!
    $available: Boolean!
    $optionIds: [ID!]!
    $variants: [ProductVariantInput!]!
    $productId: ID,
   # $attributesIds: [ID!]!
  #  $unavailableOptionsValuesIds: [ID!]!
    $displayPrice: Float!
    $imageUrl: String,
    $nullValue: DateTime
  ) {
    upsertProduct(
      name: $name
      description: $description
      imageUrl: $imageUrl
      brandId: $brandId
      categoryId: $categoryId
      available: $available
      optionIds: $optionIds
      variants: $variants
      productId: $productId
   #   attributesIds: $attributesIds
   #   unavailableOptionsValuesIds: $unavailableOptionsValuesIds
      displayPrice: $displayPrice
    ) {
      id
      name
      description
      available
      displayPrice
      imageUrl
      brand {
        id
        name
      }
      category {
        id
        name
      }
      options {
        id
        name
        values {
          id
          name
        }
      }
      variants(where: { deletedAt: $nullValue }) {
        id
        price
        available
        selectedOptions {
          id
          option {
            id
            name
          }
          value {
            id
            name
          }
        }
      }
      displayPrice
    }
}
mutation deleteProduct($name: String) {
  deleteProduct(where: { name: $name }) {
    id
    name
    description
    address
    zipCode
    city
    phoneNumber
  }
}
query product($name: String) {
  product(where: { name: $name }) {
    id
    name
    description
    address
    zipCode
    city
    phoneNumber
  }
}
query products {
  products {
    id
    name
    address
    zipCode
    city
    phoneNumber
  }
}
