mutation upsertProduct(
  $name: String!
  $namewhere: String
  $unit: String
  $code: String
  $owner: UserWhereUniqueInput
  $deals: [DealWhereUniqueInput!]
) {
  upsertProduct(
    where: { name: $namewhere }
    create: {
      name: $name
      unit: $unit
      code: $code
      owner: { connect: $owner }
      deals: { connect: $deals }
    }
    update: {
      name: $name
      unit: $unit
      code: $code
      owner: { connect: $owner }
      deals: { connect: $deals }
    }
  ) {
    id
    name
    unit
    code
    owner {
      id
      name
    }
    deals {
      id
      title
    }
  }
}
mutation deleteProduct($name: String) {
  deleteProduct(where: { name: $name }) {
    id
    name
    unit
    code
    owner {
      id
      name
    }
    deals {
      id
      title
    }
  }
}
query product($name: String) {
  product(where: { name: $name }) {
    id
    name
    unit
    code
    owner {
      id
      name
    }
    deals {
      id
      title
    }
  }
}
query products {
  products {
    id
    name
    unit
    code
    owner {
      id
      name
    }
    deals {
      id
      title
    }
  }
}
