fragment PersonFragment on Person {
  id
  name
  email
  phone
  owner {
    id
    name
  }
  pictures {
    id
  }
  products {
    id
  }
  deals {
    id
  }
}
mutation upsertPerson(
  $name: String!
  $namewhere: String
  $owner: UserWhereUniqueInput
  $email: String
  $phone: String
  $pictures: [PictureWhereUniqueInput!]
  $products: [ProductWhereUniqueInput!]
  $deals: [DealWhereUniqueInput!]
) {
  upsertPerson(
    where: { name: $namewhere }
    create: {
      name: $name
      owner: { connect: $owner }
      email: $email
      phone: $phone
      pictures: { connect: $pictures }
      products: { connect: $products }
      deals: { connect: $deals }
    }
    update: {
      name: $name
      owner: { connect: $owner }
      email: $email
      phone: $phone
      pictures: { connect: $pictures }
      products: { connect: $products }
      deals: { connect: $deals }
    }
  ) {
    ...PersonFragment
  }
}
mutation deletePerson($name: String) {
  deletePerson(where: { name: $name }) {
    ...PersonFragment
  }
}
query person($name: String) {
  person(where: { name: $name }) {
    ...PersonFragment
  }
}
query persons {
  persons {
    ...PersonFragment
  }
}

subscription personsub($where: PersonSubscriptionWhereInput) {
  person(where: $where) {
    mutation
    node {
      ...PersonFragment
    }
    updatedFields
    previousValues {
      id
      name
    }
  }
}
