mutation upsertOption(
    $id: ID
    $name: String!
    $values: [OptionValue!]!
    $category: Category!
    shop: Shop!
  ) {
    upsertOption(
    where: { id: $id }
    create: {
      name: $name
      values: $values
      category: $category
      shop: $shop
    }
    update: {
      name: $name
      values: $values
      category: $category
      shop: $shop
    }
    ) {
      id
      name
      values{
        id
        name
      }
      shop {
        id
        name
      }
      category {
        id
        name
      }
      }
      }

mutation deleteOption($id: ID!) {
  deleteOption(where: { id: $id }) {
    id
    name
  }
}
query option($id: ID!) {
  option(where: { id: $id }) {
      id
      name
      shop {
        id
        name
      }
      category {
        id
        name
      }
      values{ 
        id
        name
      }
      }
  }
query options {
  options {
    id
    name
      shop {
        id
        name
      }
      category {
        id
        name
      }
      values{ 
        id
        name
      }
  }
}