mutation upsertPipeline(
  $name: String!
  $namewhere: String
  $order_nr: String
  $deal_probability: Probability
  $deals: [DealWhereUniqueInput!]
) {
  upsertPipeline(
    where: { name: $namewhere }
    create: {
      name: $name
      order_nr: $order_nr
      deal_probability: $deal_probability
      deals: { connect: $deals }
    }
    update: {
      name: $name
      order_nr: $order_nr
      deal_probability: $deal_probability
      deals: { connect: $deals }
    }
  ) {
    id
    name
    deals {
      id
    }
    order_nr
    deal_probability
  }
}
mutation deletePipeline($name: String) {
  deletePipeline(where: { name: $name }) {
    id
    name
    deals {
      id
    }
    order_nr
    deal_probability
  }
}
query pipeline($name: String) {
  pipeline(where: { name: $name }) {
    id
    name
    deals {
      id
    }
    order_nr
    deal_probability
  }
}
query pipelines {
  pipelines {
    id
    name
    deals {
      id
    }
    order_nr
    deal_probability
  }
}
