fragment PipelineFragment on Pipeline {
    id
    name
    deals {
      id
    }
    order_nr
    deal_probability
  }


mutation upsertPipeline(
  $name: String!
  $namewhere: String
  $order_nr: String
  $deal_probability: Probability
  $deals: [DealWhereUniqueInput!]
) {
  upsertPipeline(
    where: { name: $namewhere }
    create: {
      name: $name
      order_nr: $order_nr
      deal_probability: $deal_probability
      deals: { connect: $deals }
    }
    update: {
      name: $name
      order_nr: $order_nr
      deal_probability: $deal_probability
      deals: { connect: $deals }
    }
  ) {
    ...PipelineFragment
  }
}
mutation deletePipeline($name: String) {
  deletePipeline(where: { name: $name }) {
    ...PipelineFragment
  }
}
query pipeline($name: String) {
  pipeline(where: { name: $name }) {
    ...PipelineFragment
  }
}
query pipelines {
  pipelines {
    ...PipelineFragment
  }
}

subscription pipelinesub($where: PipelineSubscriptionWhereInput) {
  pipeline(where: $where) {
    node {
      ...PipelineFragment
    }
    updatedFields
    previousValues {
      id
      name
    }
  }
}
